context:
  version: "1.5.0" # TODO: obtain this from package directly

package:
  name: deimos
  version: ${{ version }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - bioconda

build:
  noarch: python
  number: 0
  script: python -m pip install -vv --no-deps .
  python:
    entry_points:
      - deimos = deimos.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - dask
    - h5py
    - hdf5plugin
    - matplotlib
    - numpy
    - pandas
    - pymzml
    - pytables
    - python
    - ripser =0.6.10
    - scikit-learn
    - scipy
    - snakemake <8
    - statsmodels
    - tabula-py
